# Generated by Django 2.1.4 on 2019-01-27 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('pass_id', models.CharField(max_length=26, primary_key=True, serialize=False, verbose_name='ID')),
                ('pw', models.CharField(max_length=300, verbose_name='パスワード')),
                ('purpose', models.TextField(blank=True, max_length=100, verbose_name='使用場所')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='補足')),
                ('pw_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
