# Generated by Django 2.1.4 on 2019-01-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='pw',
            field=models.CharField(max_length=300, verbose_name='パスワード'),
        ),
    ]
